<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>PolarisSave</AssemblyName>
    <RootNamespace>Polaris.Save</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\PolarisCore\PolarisCore.csproj" /></ItemGroup>
</Project>
